#%RAML 1.0
title: New API
types:
  data:
    properties:
      Userdetails:
        items:
          properties:
            post_id:
              example: 1
              type: number
              format: int
            id:
              example: 1978
              type: number
              format: int
            name:
              example: Bhaaswar Pothuvaal III
              type: string
/milestone1: {}
